# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pfpop_interface <- function(degrees_vec, penalty, weight_vec) {
    .Call('_pfpop_pfpop_interface', PACKAGE = 'pfpop', degrees_vec, penalty, weight_vec)
}

