# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pfpop_map_interface <- function(degrees_vec, penalty, weight_vec, verbose_file) {
    .Call('_pfpop_pfpop_map_interface', PACKAGE = 'pfpop', degrees_vec, penalty, weight_vec, verbose_file)
}

pfpop_list_interface <- function(degrees_vec, penalty, weight_vec) {
    .Call('_pfpop_pfpop_list_interface', PACKAGE = 'pfpop', degrees_vec, penalty, weight_vec)
}

